spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  cache:
    jcache:
      config: classpath:ehcache.xml
    redis:
      cache-null-values: false
      use-key-prefix: true
#logging:
#  level:
#    org:
#      springframework: debug