
    create table user (
       id bigint generated by default as identity,
        age integer,
        name varchar(50),
        primary key (id)
    )

    create table user (
       id bigint generated by default as identity,
        age integer,
        name varchar(50),
        primary key (id)
    )

    create table user (
       id bigint generated by default as identity,
        age integer,
        name varchar(50),
        primary key (id)
    )
