spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1/mem:rest
    username: sa
    password:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create