spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ENC(3HNOeOw62KXKgX/SJr8vRgXrXnVfTCphHtK7++hy4DKVliop08b43LvS5AcYMRkK)
    platform: mysql

jasypt:
  encryptor:
#    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: elliot
#    ivGeneratorClassname: org.jasypt.iv.RandomIvGenerator
