spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: abcd1234
    platform: mysql
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    "liquibase" : INFO