spring:
  datasource:
    url: jdbc:h2:file:~/data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  liquibase:
    enabled: true
logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    "liquibase" : INFO