management:
  metrics:
    export:
      prometheus:
        enabled: true
#  endpoint:
#    prometheus:
#      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

