version: "3.3"

services:

  redis-master:
    container_name: redis-master
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-master:/data

  redis-slave:
    container_name: redis-slave
    image: redis:5-alpine
    command: redis-server --slaveof redis-master 6379
    ports:
      - 6380:6379
    volumes:
      - ./data/redis-slave:/data
    links:
      - redis-master

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=master:redis-master,slave-1:redis-slave
    ports:
    - 8081:8081