#
#spring:
#  profiles:
#    active: demo
spring:
  application:
    name: 06profile
---
spring:
  profiles: prod

server:
  port: 8080

---
spring:
  profiles: stage

server:
  port: 9080

---
spring:
  profiles: dev

server:
  port: 7080
