
res:
  entryResultPath: "/Users/elliot/IdeaProjects/spring_boot_example/29tcpserver/src/main/resources"
  charEncoding: "BIG5"
  fileExtension: "txt"
logging:
  level:
    tw:
      elliot:
        tcpserver:
          support: DEBUG
